### ISSUE TITLE
Feature request: Snapshot multiple subvolumes

### ISSUE THREAD

**Issue by Fogelholk** [markmcb/btrfs_snapshot_rotate#2]
As the subject says, would be awesome to have "one script to snapshot them all" :)

**Comment by markmcb** [comment]
This is possible if you add hashes to the SnapshotConfigurations array, e.g., by default it's SC = [{subvol info}], but you can add all the hashes you want, SC = [{subvol1 info}, {subvol2 info}, {subvol3 info}]

**Comment by Fogelholk** [comment]
Thanks! You should definitely add this to the readme!

**Comment by markmcb** [comment]
Done! Thanks for the suggestion.
